apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: xgk4mqfq0-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/xgk4mqfq0-java-springboot-gitops